INSERT INTO CARD_YEAR (CARD_YEAR) VALUES  (1982), (1983), (1984),
  (1985), (1986), (1987), (1988), (1989), (1990), (1991), (1992),
  (1993), (1994), (1995), (1996), (1997), (1998), (1999), (2000),
  (2001), (2002), (2003), (2004), (2005), (2006), (2007), (2008),
  (2009), (2010), (2011), (2012), (2013), (2014), (2015), (2016),
  (2017);

INSERT INTO TEAM (CITY, TEAM_NAME) VALUES ('New York', 'Yankees'), ('Cincinnati', 'Reds'),
  ('Seattle', 'Mariners'), ('Washington', 'Nationals'), ('Boston', 'Red Sox'), ('Baltimore', 'Orioles'),
  ('Tampa Bay', 'Rays'), ('Toronto', 'Blue Jays'), ('Chicago', 'White Sox'), ('Cleveland', 'Indians'),
  ('Kansas City', 'Royals'), ('Minnesota', 'Twins'), ('Detroit', 'Tigers'), ('Los Angeles', 'Angels'),
  ('Houston', 'Astros'), ('Texas', 'Rangers'), ('Oakland', 'Athletics'), ('New York', 'Mets'),
  ('Philadelphia', 'Phillies'), ('Miami', 'Marlins'), ('Atlanta', 'Braves'), ('Chicago', 'Cubs'),
  ('Pittsburgh', 'Pirates'), ('Milwaukee', 'Brewers'), ('St. Louis', 'Cardinals'), ('Los Angeles', 'Dodgers'),
  ('San Francisco', 'Giants'), ('San Diego', 'Padres'), ('Arizona', 'Diamondbacks'), ('Colorado', 'Rockies'),
  ('', 'Not a player'), ('Japan', 'National Team'), ('New York', 'Giants');

INSERT INTO BRAND (BRAND_NAME) VALUES ('Topps'), ('Upper Deck'), ('Fleer'), ('Bowman'), ('TriStar'),
('Donruss'), ('Team Best'), ('Flair'), ('Just Minors');

INSERT INTO PLAYER (FIRST_NAME, LAST_NAME, DOB) VALUES ('Derek', 'Jeter', '1974-06-26'),
('Ichiro', 'Suzuki', '1973-10-22'), ('Ryan', 'Zimmerman', '1984-09-28'), ('Alex', 'Rodriguez', '1975-07-27'),
('Giancarlo', 'Stanton', '1989-11-08'), ('George', 'Springer', '1989-09-19'), ('Yoshimoto', 'Tsutsugoh', '1991-11-26'),
('Steve', 'Stone', '1947-07-14'), ('Bo', 'Jackson', '1962-11-30'), ('Rickey', 'Henderson', '1958-12-25'),
('Ozzie', 'Smith', '1954-12-26'), ('Dale', 'Murphy', '1956-03-12'), ('Ryan', 'Rupe', '1975-03-31'),
('Magglio', 'Ordonez', '1974-01-28'), ('Todd', 'Walker', '1973-05-25'), ('Randy', 'Johnson', '1963-09-10'),
('Luis', 'Gonzalez', '1967-09-03'), ('Chipper', 'Jones', '1972-04-24'), ('Jim', 'Thome', '1970-08-27'),
('Juan', 'Gonzalez', '1969-10-20'), ('Roberto', 'Alomar', '1968-02-05'), ('Joe', 'Borchard', '1978-11-25'),
('J.D.', 'Drew', '1975-11-20'), ('Mike', 'Piazza', '1968-09-08'), ('Andruw', 'Jones', '1977-04-23'),
('Francisco', 'Cruceta', '1981-07-04'), ('Frank', 'Thomas', '1968-05-27'), ('Nomar', 'Garciaparra', '1973-07-23'),
('Austin', 'Kearns', '1980-05-20'), ('Jason', 'Giambi', '1971-01-08'), ('Jimmy', 'Journell', '1977-12-29'),
('George', 'Brett', '1953-05-15');

INSERT INTO PLAYER (FIRST_NAME, LAST_NAME, SUFFIX, DOB) VALUES ('Ken', 'Griffey', 'Jr.', '1969-11-21'),
                                                               ('Ken', 'Griffey', 'Sr.', '1950-04-10'),
                                                               ('Rickie', 'Weeks', 'Jr.', '1982-09-13');

INSERT INTO CARD_SET (YEAR_ID, BRAND_ID) VALUES ((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 1982), 6),
((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 1986), 1), ((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 1990), 4),
((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 1993), 2), ((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2006), 1),
((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2007), 1), ((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2008), 1),
((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2001), 7);

INSERT INTO CARD_SET (YEAR_ID, BRAND_ID, SET_NAME) VALUES ((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 1992), 3, 'Ultra'),
((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2000), 3, 'Ultra'), ((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2001), 3, 'Legacy'),
((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2001), 3, 'Platinum'), ((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2001), 2, 'Gold Glove'),
((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2007), 2, 'Masterpieces'), ((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2008), 2, 'Masterpieces'),
((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2017), 1, 'Allen & Ginter'), ((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2001), 2, 'SP Game Used Edition'),
((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2001), 2, 'SPX'), ((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2002), 8, 'Base Set'),
((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2002), 3, 'Maximum'), ((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2002), 2, 'Diamond Connection'),
((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2002), 9, 'Just Rookies'), ((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2003), 1, 'Tribute Contemporary Collection'),
((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2003), 2, 'Sweet Spot'), ((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2003), 4, 'Draft Picks & Prospects'),
((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2004), 1, 'Cracker Jack'), ((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2004), 1, 'Total'),
((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2004), 3, 'Greats');

INSERT INTO CARD (SET_ID, PLAYER_ID, TEAM_ID, CARD_NUM) VALUES (2, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Bo' AND LAST_NAME = 'Jackson'),
                                                                   (SELECT id FROM TEAM WHERE TEAM_NAME = 'Royals'), '50T'),
                                                               (3, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Rickey' AND LAST_NAME = 'Henderson'),
                                                                   (SELECT id FROM TEAM WHERE CITY = 'Oakland'), '457'),
                                                               (9, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Ozzie' AND LAST_NAME = 'Smith'),
                                                                   (SELECT id FROM TEAM WHERE TEAM_NAME = 'Cardinals'), '271'),
                                                               (4, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Dale' AND LAST_NAME = 'Murphy'),
                                                                   (SELECT id FROM TEAM WHERE TEAM_NAME = 'Phillies'), '32');


INSERT INTO CARD (SET_ID, PLAYER_ID, TEAM_ID, CARD_NUM, MEM_TYPE) VALUES (1, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Steve' AND LAST_NAME = 'Stone'),
                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Orioles'), '357', 'Autograph');

INSERT INTO CARD (SET_ID, PLAYER_ID, TEAM_ID, CARD_NUM, INSERT_TYPE, MEM_TYPE) VALUES (16, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Giancarlo' AND LAST_NAME = 'Stanton'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Marlins'), 'GS', 'Full-Size Relic Design A', 'Relic'),
                                                                                      (16, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'George' AND LAST_NAME = 'Springer'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Astros'), 'GSP', 'Full-Size Relic Design B', 'Relic'),
                                                                                      (11, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Magglio'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'White Sox'), '23', 'Hit Kings', 'Bat'),
                                                                                      (12, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Todd' AND LAST_NAME = 'Walker'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Rockies'), 'TOWA', 'National Patch Time', 'Relic'),
                                                                                      (13, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Randy' AND LAST_NAME = 'Johnson'),
                                                                                          (SELECT id FROM TEAM WHERE CITY = 'Arizona'), 'JG', 'Official Issue Game Ball', 'Relic'),
                                                                                      (13, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Luis' AND LAST_NAME = 'Gonzalez'),
                                                                                          (SELECT id FROM TEAM WHERE CITY = 'Arizona'), 'JG', 'Official Issue Game Ball', 'Relic'),
                                                                                      (17, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Chipper'),
                                                                                          (SELECT id FROM TEAM WHERE CITY = 'Atlanta'), 'CJ', 'Authentic Fabric', 'Relic'),
                                                                                      (18, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Thome'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Indians'), 'TGA', 'Winning Materials', 'Triple Relic'),
                                                                                      (18, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Gonzalez' AND FIRST_NAME = 'Juan'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Indians'), 'TGA', 'Winning Materials', 'Triple Relic'),
                                                                                      (18, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Alomar'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Indians'), 'TGA', 'Winning Materials', 'Triple Relic'),
                                                                                      (20, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Piazza'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Mets'), 'MIPI', 'America''s Game', 'Relic'),
                                                                                      (23, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Frank' AND LAST_NAME = 'Thomas'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'White Sox'), 'FT', 'Tribute to the Stars', 'Dual Relic'),
                                                                                      (19, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'J.D.'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Cardinals'), 'JDDR', 'Jersey Heights', 'Relic');

INSERT INTO CARD (SET_ID, PLAYER_ID, TEAM_ID, CARD_NUM, INSERT_TYPE, SERIAL_NUM, MEM_TYPE) VALUES (16, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Yoshimoto' AND LAST_NAME = 'Tsutsugoh'),
                                                                                                      (SELECT id FROM TEAM WHERE CITY = 'Japan'), 'YT', 'World Baseball Classic Relic', '92/99', 'Relic'),
                                                                                                  (10, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Ryan' AND LAST_NAME = 'Rupe'),
                                                                                                      (SELECT id FROM TEAM WHERE TEAM_NAME = 'Rays'), '51', 'Fresh Ink', '613/1000', 'Autograph'),
                                                                                                  (21, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Andruw'),
                                                                                                      (SELECT id FROM TEAM WHERE TEAM_NAME = 'Braves'), '559', 'Diamond Connection', '429/775', 'Relic');

INSERT INTO CARD (SET_ID, PLAYER_ID, TEAM_ID, CARD_NUM, SERIAL_NUM, MEM_TYPE) VALUES (8, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Borchard'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'White Sox'), '2', '20/150', 'Autograph'),
                                                                                     (22, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Cruceta'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Dodgers'), '5', '281/400', 'Autograph');

INSERT INTO PLAYER (FIRST_NAME, LAST_NAME, DOB) VALUES ('Jamie', 'Moyer', '1962-11-18'), ('Jeff', 'Baker', '1981-06-21'), ('Chad', 'Orvella', '1980-10-01'),
('Carlos', 'Beltran', '1977-04-24'), ('Tim', 'Hudson', '1974-04-14'), ('Bret', 'Boone', '1969-04-06'), ('Josh', 'Beckett', '1980-05-15'),
('Mark', 'Prior', '1980-09-07'), ('Roy', 'Oswalt', '1977-08-29'), ('Rafael', 'Palmeiro', '1964-09-24'), ('Paul', 'Maholm', '1982-06-25'),
('Johan', 'Santana', '1979-03-13'), ('Brooks', 'Robinson', '1937-05-18'), ('Nick', 'Punto', '1977-11-08'), ('Brian', 'Roberts', '1977-10-09'),
('Eric', 'Gagne', '1976-01-07'), ('David', 'Ortiz', '1975-11-18'), ('Ryan', 'Howard', '1979-11-19'), ('Chris', 'Shelton', '1980-06-26'),
('Eric', 'Hurley', '1985-09-17'), ('Jeff', 'Locke', '1987-11-20'), ('Sung-Wei' ,'Tseng', '1984-12-28'), ('Mark', 'Melancon', '1985-03-28'),
('Jesus', 'Montero', '1989-11-28'), ('Ronny', 'Paulino', '1981-04-21'), ('Aaron', 'Harang', '1978-05-09'), ('Joe', 'Mauer', '1983-04-19'),
('Miguel', 'Tejada', '1974-05-25'), ('Akinori', 'Iwamura', '1979-02-09'), ('Hanley', 'Ramirez', '1983-12-23'), ('Jake', 'Peavy', '1981-05-31'),
('Curt', 'Schilling', '1966-11-14'), ('Jose', 'Reyes', '1986-06-11'), ('Rajai', 'Davis', '1980-10-19'), ('Glen', 'Perkins', '1983-03-02'),
('Julio', 'Borbon', '1986-02-20'), ('Craig', 'Biggio', '1965-12-14'), ('Chris', 'Young', '1979-05-25'), ('Alex', 'Gordon', '1984-02-10'),
('Adam', 'Lind', '1983-07-17'), ('Joe', 'Smith', '1984-03-22'), ('Ryan', 'Sweeney', '1985-02-20'), ('Kory', 'Casto', '1981-12-08'),
('Matt', 'Dominguez', '1989-08-28'), ('Brad', 'Lincoln', '1985-05-25'), ('Clay', 'Buchholz', '1984-08-14'), ('Max', 'Sapp', '1988-02-21'),
('Carlos', 'Carrasco', '1987-03-21'), ('Brett', 'Sinkbeil', '1984-12-26'), ('Cooper', 'Brannan', '1984-11-07'), ('Chris', 'Coghlan', '1985-06-18'),
('Chris', 'Volstad', '1986-09-23'), ('Colton', 'Willems', '1988-07-30'), ('Josh', 'Papelbon', '1983-06-24'), ('Matt', 'Antonelli', '1985-04-08'),
('Matt', 'Sweeney', '1088-04-04'), ('Edwin', 'Encarnacion', '1983-01-07'), ('Kerry', 'Wood', '1977-06-16'), ('Felipe', 'Paulino', '1983-10-05'),
('Joey', 'Votto', '1983-09-10'), ('Daric', 'Barton', '1985-08-16'), ('Kelly', 'Pavlik', '1982-04-14'), ('Ross', 'Ohlendorf', '1982-08-08'),
('Eddie', 'Murray', '1956-02-24'), ('Mel', 'Ott', '1909-03-02'), ('Ted', 'Williams', '1918-08-30'), ('Carl', 'Yastrzemski', '1939-08-22'),
('Stan', 'Musial', '1920-11-21'), ('Troy', 'Patton', '1985-09-03'), ('Ben', 'Francisco', '1981-10-23'), ('Nick', 'Markakis', '1983-11-17'),
('Paul', 'Konerko', '1976-03-05'), ('David', 'Wells', '1963-05-20'), ('Pedro', 'Martinez', '1971-10-25'), ('Rod', 'Carew', '1945-10-01'),
('Brandon', 'Phillips', '1981-06-28'), ('John', 'Maine', '1981-05-08'), ('Bartolo', 'Colon', '1973-05-24'), ('Jeremy', 'Sowers', '1983-05-17'),
('Joe', 'Pepitone', '1940-10-09'), ('Craig', 'Stansberry', '1982-03-08'), ('Jim', 'Hunter', '1946-04-08'), ('Ken', 'Caminiti', '1963-04-21'),
('Francisco', 'Liriano', '1983-10-26'), ('Barry', 'Zito', '1978-05-13'), ('Johnny', 'Damon', '1973-11-05'), ('Robinson', 'Cano', '1982-10-22'),
('Melvin', 'Mora', '1972-02-02'), ('Carlos', 'Guillen', '1975-09-30');

INSERT INTO CARD_SET (YEAR_ID, BRAND_ID) VALUES ((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2004), 2), ((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2005), 2),
((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2006), 3), ((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2006), 2), ((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2007), 2);

INSERT INTO CARD_SET (YEAR_ID, BRAND_ID, SET_NAME) VALUES ((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2004), 6, 'Diamond Kings'), ((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2005), 1, 'Pristine'),
((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2005), 2, 'Sweet Spot'), ((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2005), 4, 'Draft Picks & Prospects'),
((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2005), 6, 'Prime Patches'), ((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2006), 1, 'Updates & Highlights'),
((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2006), 1, 'Heritage'), ((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2006), 2, 'Ovation'),
((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2006), 4, 'Draft Picks & Prospects'), ((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2006), 9, 'Just Rookies'),
((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2007), 1, 'Moments & Milestones'), ((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2007), 1, 'Turkey Red'),
((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2007), 3, 'Ultra'), ((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2007), 2, 'Artifacts'),
((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2007), 4, 'Heritage'), ((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2007), 4, 'Sterling'),
((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2007), 2, 'SP Authentic'), ((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2007), 2, 'SP Rookie Edition'),
((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2007), 5, 'Prospects Plus'), ((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2007), 5, 'Elegance'),
((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2008), 1, 'Updates & Highlights'), ((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2008), 1, 'Co-Signers'),
((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2008), 1, 'Moments & Milestones'), ((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2008), 1, 'Sterling'),
((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2008), 1, 'Triple Threads');

INSERT INTO CARD_SET (YEAR_ID, BRAND_ID) VALUES ((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2008), 2);

INSERT INTO CARD_SET (YEAR_ID, BRAND_ID, SET_NAME) VALUES ((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2008), 2, 'Spectrum'), ((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2008), 2, 'Timeline'),
((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2008), 5, 'Signa Cuts'), ((SELECT id FROM CARD_YEAR WHERE CARD_YEAR = 2008), 2, 'Ballpark Collection');

INSERT INTO CARD (SET_ID, PLAYER_ID, TEAM_ID, CARD_NUM) VALUES (52, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Dominguez'),
                                                                    (SELECT id FROM TEAM WHERE TEAM_NAME = 'Marlins'), 10);

INSERT INTO CARD (SET_ID, PLAYER_ID, TEAM_ID, CARD_NUM, MEM_TYPE) VALUES (37, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Maholm'),
                                                                              (SELECT id FROM TEAM WHERE TEAM_NAME = 'Pirates'), '127', 'Relic'),
                                                                         (43, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Locke'),
                                                                              (SELECT id FROM TEAM WHERE TEAM_NAME = 'Braves'), '27', 'Autograph'),
                                                                         (49, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Perkins'),
                                                                              (SELECT id FROM TEAM WHERE TEAM_NAME = 'Twins'), 'GP', 'Autograph'),
                                                                         (49, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Borbon'),
                                                                              (SELECT id FROM TEAM WHERE TEAM_NAME = 'Rangers'), 'JBO', 'Autograph'),
                                                                         (51, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Ryan' AND LAST_NAME = 'Sweeney'),
                                                                              (SELECT id FROM TEAM WHERE TEAM_NAME = 'White Sox'), '156', 'Autograph'),
                                                                         (51, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Casto'),
                                                                              (SELECT id FROM TEAM WHERE TEAM_NAME = 'Nationals'), '245', 'Autograph'),
                                                                         (62, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Pepitone'),
                                                                              (SELECT id FROM TEAM WHERE TEAM_NAME = 'Yankees'), 'n/a', 'Autograph'),
                                                                         (62, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Stansberry'),
                                                                              (SELECT id FROM TEAM WHERE TEAM_NAME = 'Padres'), 'n/a', 'Autograph');

INSERT INTO CARD (SET_ID, PLAYER_ID, TEAM_ID, CARD_NUM, PARALLEL_TYPE, SERIAL_NUM, MEM_TYPE) VALUES (43, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Tseng'),
                                                                                                        (SELECT id FROM TEAM WHERE TEAM_NAME = 'Indians'), '48', 'Silver Parallel', '003/100', 'Autograph'),
                                                                                                    (49, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Biggio'),
                                                                                                        (SELECT id FROM TEAM WHERE TEAM_NAME = 'Astros'), 'CAB', 'Refractor Parallel', '020/199', 'Relic'),
                                                                                                    (55, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Felipe' AND LAST_NAME = 'Paulino'),
                                                                                                        (SELECT id FROM TEAM WHERE TEAM_NAME = 'Astros'), '111', 'Silver Gold Parallel', '017/150', 'Autograph'),
                                                                                                    (62, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Hunter'),
                                                                                                        (SELECT id FROM TEAM WHERE TEAM_NAME = 'Athletics'), 'n/a', 'Red Parallel', '10/25', 'Autograph'),
                                                                                                    (62, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Caminiti'),
                                                                                                        (SELECT id FROM TEAM WHERE TEAM_NAME = 'Padres'), 'n/a', 'Purple Parallel', '1/1', 'Autograph');

INSERT INTO CARD (SET_ID, PLAYER_ID, TEAM_ID, CARD_NUM, INSERT_TYPE, MEM_TYPE) VALUES (24, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Garciaparra'),
                                                                                          (SELECT id FROM TEAM WHERE CITY = 'Boston'), 'NG1', 'Sweet Spot Swatches', 'Relic'),
                                                                                      (25, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Kearns'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Reds'), 'AK', 'Prospect Premiums', 'Relic'),
                                                                                      (26, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Giambi'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Yankees'), 'JGA', 'Take Me Out To The Ball Game', 'Relic'),
                                                                                      (27, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Journell'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Cardinals'), 'JJ', 'Total Signatures', 'Autograph'),
                                                                                      (28, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'George' AND LAST_NAME = 'Brett'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Royals'), 'GB', 'The Glory Of Their Time', 'Relic'),
                                                                                      (29, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Jamie' AND LAST_NAME = 'Moyer'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Mariners'), 'JM', 'Awesome Honors', 'Relic'),
                                                                                      (30, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Jeter'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Yankees'), 'DJ', 'Matinee Idols', 'Relic'),
                                                                                      (30, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Beltran'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Astros'), 'CB', 'Origins', 'Relic'),
                                                                                      (30, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Tim' AND LAST_NAME = 'Hudson'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Athletics'), 'TH', 'Origins', 'Relic'),
                                                                                      (30, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Bret' AND LAST_NAME = 'Boone'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Mariners'), 'BB', 'Signature Stars', 'Autograph'),
                                                                                      (35, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Palmeiro'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Orioles'), 'RP', 'Sweet Threads', 'Relic'),
                                                                                      (39, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Johan' AND LAST_NAME = 'Santana'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Twins'), 'JS', 'All-Star Stitches', 'Relic'),
                                                                                      (40, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Brooks'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Orioles'), 'BR', 'Flashbacks', 'Relic'),
                                                                                      (31, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Mark' AND LAST_NAME = 'Prior'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Cubs'), 'MP', 'Fleer Fabrics', 'Relic'),
                                                                                      (32, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Punto'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Twins'), 'NP', 'Signature Sensations', 'Autograph'),
                                                                                      (32, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Brian' AND LAST_NAME = 'Roberts'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Orioles'), 'BR', 'UD Game Materials', 'Relic'),
                                                                                      (32, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Gagne'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Dodgers'), 'EG', 'UD Game Materials', 'Relic'),
                                                                                      (32, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Prior'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Cubs'), 'PR', 'UD Game Materials', 'Relic'),
                                                                                      (32, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Palmeiro'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Orioles'), 'RP', 'UD Game Materials', 'Relic'),
                                                                                      (41, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'David' AND LAST_NAME = 'Ortiz'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Red Sox'), 'DO', 'Ovation Apparel', 'Relic'),
                                                                                      (41, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Ryan' AND LAST_NAME = 'Howard'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Phillies'), 'RH', 'Ovation Apparel', 'Relic'),
                                                                                      (41, (SELECT id FROM PLAYER WHERE FIRST_NAMe = 'Chris' AND LAST_NAME = 'Shelton'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Tigers'), 'CS', 'Ovation Spotlight Signatures', 'Autograph'),
                                                                                      (42, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Hurley'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Rangers'), '29', 'Futures Game', 'Relic'),
                                                                                      (6,  (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Alex' AND LAST_NAME = 'Rodriguez'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Yankees'), 'AR2', 'Highlights Relics', 'Relic'),
                                                                                      (44, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Ronny' AND LAST_NAME = 'Paulino'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Pirates'), 'RP', 'Milestone Autographs', 'Autograph'),
                                                                                      (45, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Harang'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Reds'), 'AH', 'Turkey Red Relics', 'Relic'),
                                                                                      (46, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Mauer'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Twins'), 'JM', 'Swing Kings', 'Relic'),
                                                                                      (33, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Tejada'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Orioles'), 'MT', 'UD Game Materials', 'Relic'),
                                                                                      (14, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Akinori'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Rays'), 'AI', 'Captured On Canvas', 'Relic'),
                                                                                      (14, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Jeter'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Yankees'), 'DJ', 'Captured On Canvas', 'Relic'),
                                                                                      (14, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Chipper'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Braves'), 'CJ', 'Captured On Canvas', 'Relic'),
                                                                                      (14, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Hanley'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Marlins'), 'HR', 'Stroke Of Genius', 'Autograph'),
                                                                                      (48, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Schilling'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Red Sox'), 'CS', 'Pieces Of Greatness', 'Relic'),
                                                                                      (48, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Jose' AND LAST_NAME = 'Reyes'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Mets'), 'JR', 'Pieces Of Greatness', 'Relic'),
                                                                                      (48, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Rajai'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Pirates'), 'RD', 'Signs Of Greatness', 'Autograph'),
                                                                                      (53, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Lincoln'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Pirates'), 'BL', 'Showtime', 'Relic'),
                                                                                      (53, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Buchholz'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Red Sox'), 'CLL', 'Showtime', 'Relic'),
                                                                                      (53, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Max' AND LAST_NAME = 'Sapp'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Astros'), 'MS', 'Showtime', 'Relic'),
                                                                                      (53, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Sinkbeil'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Marlins'), 'BS', 'Signature Marks', 'Autograph'),
                                                                                      (53, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Brannan'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Padres'), 'CB', 'Signature Marks', 'Autograph'),
                                                                                      (53, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Coghlan'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Marlins'), 'CC2', 'Signature Marks', 'Autograph'),
                                                                                      (53, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Volstad'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Marlins'), 'CV', 'Signature Marks', 'Autograph'),
                                                                                      (53, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Willems'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Nationals'), 'CW', 'Signature Marks', 'Autograph'),
                                                                                      (53, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Josh' AND LAST_NAME = 'Papelbon'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Red Sox'), 'JP2', 'Signature Marks', 'Autograph'),
                                                                                      (53, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Antonelli'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Padres'), 'MA', 'Signature Marks', 'Autograph'),
                                                                                      (53, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Matt' AND LAST_NAME = 'Sweeney'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Angels'), 'MS', 'Signature Marks', 'Autograph'),
                                                                                      (7, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Encarnacion'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Reds'), 'EE', 'Retail Relics', 'Relic'),
                                                                                      (55, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Votto'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Reds'), 'VC', 'Co-Signers Autographs', 'Dual Autograph'),
                                                                                      (55, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Barton'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Athletics'), 'VC', 'Co-Signers Autographs', 'Dual Autograph'),
                                                                                      (55, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Pavlik'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Not a player'), 'KP', 'Solo Sigs', 'Autograph'),
                                                                                      (56, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Rodriguez'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Yankees'), 'AR', '500 HR Wall Relic', 'Relic'),
                                                                                      (56, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Barton'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Athletics'), 'DB', 'Rookie Autographs', 'Autograph'),
                                                                                      (56, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Ohlendorf'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Yankees'), 'RO', 'Rookie Autographs', 'Autograph'),
                                                                                      (59, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Ben' AND LAST_NAME = 'Francisco'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Indians'), 'BF', 'Season Highlights Signatures', 'Autograph'),
                                                                                      (59, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Markakis'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Orioles'), 'NM', 'UD Game Jersey 1998 Throwback', 'Relic'),
                                                                                      (59, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Konerko'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'White Sox'), 'PK', 'UD Game Jersey 1998 Throwback', 'Relic'),
                                                                                      (59, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'David' AND LAST_NAME = 'Wells'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Dodgers'), 'DW', 'UD Game Jersey 1999 Throwback', 'Relic'),
                                                                                      (15, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Pedro' AND LAST_NAME = 'Martinez'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Mets'), 'PM', 'Captured On Canvas', 'Relic'),
                                                                                      (15, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Phillips'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Reds'), 'BP', 'Stroke Of Genius', 'Autograph'),
                                                                                      (15, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Maine'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Mets'), 'MA', 'Stroke Of Genius', 'Autograph'),
                                                                                      (60, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Bartolo' AND LAST_NAME = 'Colon'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'White Sox'), 'BC2', 'Retrospectrum Swatches', 'Relic'),
                                                                                      (61, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Sowers'),
                                                                                          (SELECT id FROM TEAM WHERE TEAM_NAME = 'Indians'), 'JS', 'Timeline Memorabilia', 'Relic');

INSERT INTO CARD (SET_ID, PLAYER_ID, TEAM_ID, CARD_NUM, INSERT_TYPE, SERIAL_NUM, MEM_TYPE) VALUES (38, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'J.D.' AND LAST_NAME = 'Drew'),
                                                                                                      (SELECT id FROM TEAM WHERE TEAM_NAME = 'Cardinals'), '50', 'Major League Materials', '025/150', 'Relic'),
                                                                                                  (34, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Jeff' AND LAST_NAME = 'Baker'),
                                                                                                      (SELECT id FROM TEAM WHERE TEAM_NAME = 'Rockies'), '87', 'DK Materials', '25/100', 'Dual Relic'),
                                                                                                  (36, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Josh' AND LAST_NAME = 'Beckett'),
                                                                                                      (SELECT id FROM TEAM WHERE TEAM_NAME = 'Marlins'), 'BPO', 'Majestic Materials', '08/25', 'Triple Relic'),
                                                                                                  (36, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Mark' AND LAST_NAME = 'Prior'),
                                                                                                      (SELECT id FROM TEAM WHERE TEAM_NAME = 'Cubs'), 'BPO', 'Majestic Materials', '08/25', 'Triple Relic'),
                                                                                                  (36, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Roy' AND LAST_NAME = 'Oswalt'),
                                                                                                      (SELECT id FROM TEAM WHERE TEAM_NAME = 'Astros'), 'BPO', 'Majestic Materials', '08/25', 'Triple Relic'),
                                                                                                  (35, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Orvella'),
                                                                                                      (SELECT id FROM TEAM WHERE TEAM_NAME = 'Rays'), 'CO', 'Personal Endorsements', '363/497', 'Autograph'),
                                                                                                  (43, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Melancon'),
                                                                                                      (SELECT id FROM TEAM WHERE TEAM_NAME = 'Yankees'), 'n/a', 'Dual Signatures', '2/2', 'Dual Autograph'),
                                                                                                  (43, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Jesus' AND LAST_NAME = 'Montero'),
                                                                                                      (SELECT id FROM TEAM WHERE TEAM_NAME = 'Yankees'), 'n/a', 'Dual Signatures', '2/2', 'Dual Autograph'),
                                                                                                  (47, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Rickie' AND LAST_NAME = 'Weeks'),
                                                                                                      (SELECT id FROM TEAM WHERE TEAM_NAME = 'Brewers'), 'RW', 'Antiquity Artifacts', '033/199', 'Relic'),
                                                                                                  (47, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Peavy'),
                                                                                                      (SELECT id FROM TEAM WHERE TEAM_NAME = 'Padres'), 'JP', 'Artifacts Apparel', '050/199', 'Relic'),
                                                                                                  (47, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Peavy'),
                                                                                                      (SELECT id FROM TEAM WHERE TEAM_NAME = 'Padres'), 'JP', 'Divisional Artifacts', '079/199', 'Relic'),
                                                                                                  (50, (SELECT id FROM PLAYER WHERE FIRST_NAMe = 'Chris' AND LAST_NAME = 'Young'),
                                                                                                      (SELECT id FROM TEAM WHERE TEAM_NAME = 'Padres'), '19', 'By The Letter Signatures', '17/75', 'Autograph'),
                                                                                                  (50, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Alex' AND LAST_NAME = 'Gordon'),
                                                                                                      (SELECT id FROM TEAM WHERE TEAM_NAME = 'Royals'), '17', 'By The Letter Signatures', '13/25', 'Autograph'),
                                                                                                  (50, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Lind'),
                                                                                                      (SELECT id FROM TEAM WHERE CITY = 'Toronto'), '119', 'By The Letter Rookie Signatures', '19/75', 'Autograph'),
                                                                                                  (50, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Joe' AND LAST_NAME = 'Smith'),
                                                                                                      (SELECT id FROM TEAM WHERE TEAM_NAME = 'Mets'), '160', 'By The Letter Rookie Signatures', '19/75', 'Autograph'),
                                                                                                  (57, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Murray'),
                                                                                                      (SELECT id FROM TEAM WHERE TEAM_NAME = 'Orioles'), 'EM06', 'Super Jumbo Patch', '1/1', 'Jumbo Relic'),
                                                                                                  (57, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Ott'),
                                                                                                      (SELECT id FROM TEAM WHERE CITY = 'New York' AND TEAM_NAME = 'Giants'),
                                                                                                      '7', 'Triple Sterling Stardom', '05/10', 'Triple Relic'),
                                                                                                  (63, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Liriano'),
                                                                                                      (SELECT id FROM TEAM WHERE TEAM_NAME = 'Twins'), '120', 'AL/NL Stars Dual Swatch', '259/400', 'Dual Relic'),
                                                                                                  (63, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Zito'),
                                                                                                      (SELECT id FROM TEAM WHERE CITY = 'San Francisco' AND TEAM_NAME = 'Giants'), '120', 'AL/NL Stars Dual Swatch', '259/400', 'Dual Relic'),
                                                                                                  (63, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Ortiz'),
                                                                                                      (SELECT id FROM TEAM WHERE TEAM_NAME = 'Red Sox'), '166', 'Teammate Timelines', '111/400', 'Dual Relic'),
                                                                                                  (63, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Beckett'),
                                                                                                      (SELECT id FROM TEAM WHERE TEAM_NAME = 'Red Sox'), '166', 'Teammate Timelines', '111/400', 'Dual Relic'),
                                                                                                  (63, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Damon'),
                                                                                                      (SELECT id FROM TEAM WHERE TEAM_NAME = 'Yankees'), '173', 'Teammate Timelines', '042/400', 'Dual Relic'),
                                                                                                  (63, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Cano'),
                                                                                                      (SELECT id FROM TEAM WHERE TEAM_NAME = 'Yankees'), '173', 'Teammate Timelines', '042/400', 'Dual Relic'),
                                                                                                  (63, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Mora'),
                                                                                                      (SELECT id FROM TEAM WHERE TEAM_NAME = 'Orioles'), '186', 'Stat Kings', '240/390', 'Dual Relic'),
                                                                                                  (63, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Guillen'),
                                                                                                      (SELECT id FROM TEAM WHERE TEAM_NAME = 'Tigers'), '186', 'Stat Kings', '240/390', 'Dual Relic');

INSERT INTO CARD (SET_ID, PLAYER_ID, TEAM_ID, CARD_NUM, INSERT_TYPE, PARALLEL_TYPE, MEM_TYPE) VALUES (53, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Carrasco'),
                                                                                                        (SELECT id FROM TEAM WHERE TEAM_NAME = 'Indians'), 'CC', 'Showtime', 'Gold Parallel', 'Relic');

INSERT INTO CARD (SET_ID, PLAYER_ID, TEAM_ID, CARD_NUM, INSERT_TYPE, PARALLEL_TYPE, SERIAL_NUM, MEM_TYPE) VALUES (54, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Wood'),
                                                                                                                  (SELECT id FROM TEAM WHERE TEAM_NAME = 'Cubs'), 'KW', 'Retail Relics', 'Gold Parallel', '90/99', 'Relic'),
                                                                                                                 (58, (SELECT id FROM PLAYER WHERE FIRST_NAME = 'Ted' AND LAST_NAME = 'Williams'),
                                                                                                                  (SELECT id FROM TEAM WHERE TEAM_NAME = 'Red Sox'), '85', 'Relic Combos', 'Sepia Parallel', '13/27', 'Triple Relic'),
                                                                                                                 (58, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Yastrzemski'),
                                                                                                                  (SELECT id FROM TEAM WHERE TEAM_NAME = 'Red Sox'), '85', 'Relic Combos', 'Sepia Parallel', '13/27', 'Triple Relic'),
                                                                                                                 (58, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Musial'),
                                                                                                                  (SELECT id FROM TEAM WHERE TEAM_NAME = 'Cardinals'), '85', 'Relic Combos', 'Sepia Parallel', '13/27', 'Triple Relic'),
                                                                                                                 (58, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Patton'),
                                                                                                                  (SELECT id FROM TEAM WHERE TEAM_NAME = 'Orioles'), '166', 'Rookies & Rising Stars Autographed Triple Relics', 'Gold Parallel', '24/25', 'Triple Relic Autograph'),
                                                                                                                 (15, (SELECT id FROM PLAYER WHERE LAST_NAME = 'Carew'),
                                                                                                                  (SELECT id FROM TEAM WHERE TEAM_NAME = 'Angels'), 'CW', 'Captured On Canvas', 'Patch Parallel', '04/25', 'Relic');

