CREATE TABLE CARD_YEAR(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  CARD_YEAR INT NOT NULL UNIQUE
);

CREATE TABLE PLAYER(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(60) NOT NULL,
  LAST_NAME VARCHAR(60) NOT NULL,
  SUFFIX VARCHAR(10) DEFAULT '',
  DOB DATE NOT NULL
);

CREATE TABLE BRAND(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  BRAND_NAME VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE CARD_SET(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  BRAND_ID BIGINT NOT NULL,
  SET_NAME VARCHAR(255) DEFAULT 'Base Set'
);

ALTER TABLE CARD_SET ADD FOREIGN KEY (BRAND_ID) REFERENCES BRAND(ID);

CREATE TABLE TEAM(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  CITY VARCHAR(255) NOT NULL,
  TEAM_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE CARD(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  YEAR_ID BIGINT NOT NULL,
  SET_ID BIGINT NOT NULL,
  CARD_NUM VARCHAR(30) NOT NULL,
  PARALLEL_NUM VARCHAR(30) DEFAULT 'n/a',
  QUANTITY INT DEFAULT 1,
  MEM_TYPE VARCHAR(255) DEFAULT 'None',
  IMAGE_NAME VARCHAR(255) NOT NULL
);

ALTER TABLE CARD ADD FOREIGN KEY (YEAR_ID) REFERENCES CARD_YEAR(ID);
ALTER TABLE CARD ADD FOREIGN KEY (SET_ID) REFERENCES CARD_SET(ID);

CREATE TABLE PLAYER_TO_CARD(
  PLAYER_ID BIGINT NOT NULL,
  CARD_ID BIGINT NOT NULL
);

ALTER TABLE PLAYER_TO_CARD ADD FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER(ID);
ALTER TABLE PLAYER_TO_CARD ADD FOREIGN KEY (CARD_ID) REFERENCES CARD(ID);

CREATE TABLE TEAM_TO_CARD(
  TEAM_ID BIGINT NOT NULL,
  CARD_ID BIGINT NOT NULL
);

ALTER TABLE TEAM_TO_CARD ADD FOREIGN KEY (TEAM_ID) REFERENCES TEAM(ID);
ALTER TABLE TEAM_TO_CARD ADD FOREIGN KEY (CARD_ID) REFERENCES CARD(ID);

CREATE INDEX IDX_PLAYER_TO_CARD ON PLAYER_TO_CARD(PLAYER_ID, CARD_ID);
CREATE INDEX IDX_TEAM_TO_CARD ON TEAM_TO_CARD(TEAM_ID, CARD_ID);
CREATE INDEX IDX_PLAYER ON PLAYER(FIRST_NAME, LAST_NAME, DOB);
CREATE INDEX IDX_SET ON CARD_SET(BRAND_ID, SET_NAME);
CREATE INDEX IDX_TEAM ON TEAM(CITY, TEAM_NAME);
CREATE INDEX IDX_CARD ON CARD(YEAR_ID, SET_ID, CARD_NUM);